import { Column, Heading, Text } from "@once-ui-system/core";
import { pageMeta, ogImageFor, person, social } from "@/resources";
import { jsonLd, webPageJsonLd } from "@/resources/schema";

export async function generateMetadata() {
  return pageMeta({ title: "Experience", description: "Review Saaim Abdullah's software engineering experience across backend APIs, full-stack products, cloud infrastructure, and data systems.", path: "/experience" });
}

const roles = [
  { company: "Fitter Health", title: "Software Engineer, Full-stack and Cloud · Contract", dates: "2026", location: "Remote · Spain-based team", bullets: ["Took a validated health-tech concept from zero to a live product used by patients and providers. Designed and built the frontend, backend, database, cloud infrastructure, and data layer, then documented and handed over the system.", "Shipped the AWS estate across ECS, RDS, S3, SNS, SQS, IAM, and VPC with containerisation, least-privilege access, and multi-availability-zone deployment.", "Defined API contracts and backend workflows; built notification and file-handling architecture on Celery and Redis, backed by 135 passing tests, reversible migrations, and database-level integrity constraints.", "Modelled membership and entitlement workflows across a 106-table PostgreSQL schema covering credit balances, session booking, e-commerce, admin CRM, and invoice status synchronisation with Odoo.", "Designed an ETL pipeline into a star-schema PostgreSQL warehouse for data-science workflows, product analytics, and partner reporting.", "Automated member lifecycle email with EventBridge-scheduled Lambda and SES, including renewal reminders and inactivity re-engagement.", "Diagnosed silent notification loss and added SQS between SNS and consumers so failed delivery became retryable with a dead-letter path."], tech: "Django · Next.js · PostgreSQL · Celery · Redis · AWS · Docker", link: "/work/fitter-health-platform" },
  { company: "Expertflow", title: "Software Engineer, Backend and Cloud", dates: "2024 – 2026", location: "Lahore · Cisco UCCE solution partner", bullets: ["Owned backend REST APIs serving 1,000–3,000 daily users, deployed as Docker containers on AWS EC2 behind an Application Load Balancer with rate limiting, scoped IAM, and VPC isolation.", "Re-deployed the backend as a distributed system on AWS EKS with Horizontal Pod Autoscaler policies that scale replicas with request throughput.", "Reduced admin panel response time from 130 ms to 30 ms through Redis caching and database-index tuning after profiling identified query cost.", "Designed and shipped event-driven batch and streaming ETL pipelines using AWS Lambda, MWAA, EMR, PySpark, Glue, and S3, producing analytics-ready Parquet for BI and ML workflows.", "Developed a real-time voice and video communication SDK on WebRTC and the REST APIs connecting frontend clients, SDK modules, and third-party platforms.", "Implemented a chatbot workflow, SQL-based customer-insight analytics, and time-bound permission controls.", "Worked across Angular frontend, backend, and SDK teams to deliver features end to end."], tech: "Python · Django · REST APIs · AWS · EKS · Redis · PySpark · WebRTC" },
];

export default function Experience() {
  return <Column maxWidth="m" paddingTop="48" paddingBottom="80" gap="48">
    <script {...jsonLd(webPageJsonLd({ title: "Experience", description: "Review Saaim Abdullah's software engineering experience across backend APIs, full-stack products, cloud infrastructure, and data systems.", path: "/experience", image: ogImageFor("Experience") }))} />
    <Column gap="12"><Text variant="label-strong-s" onBackground="brand-weak">CAREER</Text><Heading as="h1" variant="display-strong-l">Experience</Heading><Text variant="heading-default-m" onBackground="neutral-weak">Software engineering work across backend systems, full-stack products, and data-heavy applications.</Text></Column>
    <Column as="section" gap="40"><Heading as="h2" variant="display-strong-s">Employment</Heading>{roles.map((role) => <Column key={role.company} gap="12" paddingBottom="32" style={{ borderBottom: "1px solid var(--border)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 24, flexWrap: "wrap" }}><div><Heading as="h3" variant="heading-strong-l">{role.company}</Heading><Text onBackground="brand-weak">{role.title}</Text></div><div style={{ textAlign: "right" }}><Text variant="body-default-s" onBackground="neutral-weak">{role.dates}</Text><Text variant="body-default-s" onBackground="neutral-weak">{role.location}</Text></div></div><Column as="ul" gap="8" paddingTop="8">{role.bullets.map((bullet) => <Text as="li" key={bullet} variant="body-default-m">{bullet}</Text>)}</Column><Text variant="body-default-s" onBackground="neutral-weak">{role.tech}</Text>{role.link && <a className="extLink" href={role.link}>Read case study →</a>}</Column>)}</Column>
    <Column as="section" gap="16"><Heading as="h2" variant="display-strong-s">Education</Heading><Text variant="body-default-m"><strong>BS Computer Engineering</strong><br />COMSATS University Islamabad, Lahore Campus · 2021 – 2025</Text></Column>
    <Column as="section" gap="20"><Heading as="h2" variant="display-strong-s">Technical skills</Heading><div className="cardGrid cardGrid--2">{[["Backend", "Python, Django, REST APIs, Celery, SNS/SQS"], ["Frontend", "TypeScript, React, Next.js, Angular"], ["Data and databases", "PostgreSQL, Redis, MongoDB, pgvector, ETL"], ["Cloud and delivery", "AWS, Docker, Kubernetes, CI/CD, Git"]].map(([name, value]) => <div className="skillGroup" key={name}><Heading as="h3" variant="heading-strong-m">{name}</Heading><Text onBackground="neutral-weak">{value}</Text></div>)}</div></Column>
    <Column as="section" gap="16"><Heading as="h2" variant="display-strong-s">Courses & Certifications</Heading><Text variant="body-default-m">AWS Cloud Technical Essentials · Introduction to Data Engineering · Claude Code 101</Text></Column>
  </Column>;
}
